import {
	AppWindow,
	Boxes,
	Component,
	Database,
	FastForward,
	Lock,
	Palette,
	ServerCog,
	Workflow,
} from "lucide-react";

export const technologies = [
	{
		name: "Bun",
		category: "core",
		angle: -25,
		icon: FastForward,
		color: "bg-yellow-100",
		textColor: "text-black",
		description: "Fast all-in-one JavaScript runtime",
		top: "top-[2px]",
		left: "left-[10rem]",
	},
	{
		name: "tRPC",
		category: "core",
		angle: 25,
		icon: Workflow,
		color: "bg-blue-600",
		textColor: "text-white",
		description: "End-to-end type-safe APIs",
		left: "left-[5rem]",
	},

	{
		name: "TanStack Router",
		category: "frontend",
		angle: 30,
		icon: AppWindow,
		color: "bg-red-500",
		textColor: "text-white",
		description: "Type-safe routing",
		top: "top-[2px]",
		left: "left-[7.5rem]",
	},
	{
		name: "Tailwind CSS",
		category: "frontend",
		angle: 90,
		icon: Palette,
		color: "bg-sky-400",
		textColor: "text-white",
		description: "Utility-first CSS framework",
	},
	{
		name: "shadcn/ui",
		category: "frontend",
		angle: 150,
		icon: Component,
		color: "bg-gray-900",
		textColor: "text-white",
		description: "Re-usable components",
		left: "-left-[2rem]",
	},

	{
		name: "Hono",
		category: "backend",
		angle: -150,
		icon: ServerCog,
		color: "bg-orange-500",
		textColor: "text-white",
		description: "Ultrafast web framework",
		left: "left-[0rem]",
	},
	{
		name: "Better-Auth",
		category: "backend",
		angle: -110,
		icon: Lock,
		color: "bg-indigo-600",
		textColor: "text-white",
		description: "Modern authentication solution",
	},
	{
		name: "Drizzle ORM",
		category: "backend",
		angle: -70,
		icon: Database,
		color: "bg-green-400",
		textColor: "text-black",
		description: "TypeScript ORM",
	},
	{
		name: "libSQL",
		category: "backend",
		angle: -30,
		icon: Boxes,
		color: "bg-gray-600",
		textColor: "text-white",
		description: "SQLite-compatible database engine",
		left: "left-[6rem]",
	},
];
