import type { TechCategory } from "./types";

export const TECH_OPTIONS: Record<
	TechCategory,
	{
		id: string;
		name: string;
		description: string;
		icon: string;
		color: string;
		default?: boolean;
		className?: string;
	}[]
> = {
	api: [
		{
			id: "trpc",
			name: "tRPC",
			description: "End-to-end typesafe APIs",
			icon: "/icon/trpc.svg",
			color: "from-blue-500 to-blue-700",
			default: true,
		},
		{
			id: "orpc",
			name: "oRPC",
			description: "Typesafe APIs Made Simple",
			icon: "/icon/orpc.svg",
			color: "from-indigo-400 to-indigo-600",
		},
		{
			id: "none",
			name: "No API",
			description: "No API layer (API routes disabled)",
			icon: "",
			color: "from-gray-400 to-gray-600",
		},
	],
	webFrontend: [
		{
			id: "tanstack-router",
			name: "TanStack Router",
			description: "Modern type-safe router for React",
			icon: "/icon/tanstack.svg",
			color: "from-blue-400 to-blue-600",
			default: true,
		},
		{
			id: "react-router",
			name: "React Router",
			description: "Declarative routing for React",
			icon: "/icon/react-router.svg",
			color: "from-cyan-400 to-cyan-600",
			default: false,
		},
		{
			id: "tanstack-start",
			name: "TanStack Start (vite)",
			description:
				"Full-stack React and Solid framework powered by TanStack Router",
			icon: "/icon/tanstack.svg",
			color: "from-purple-400 to-purple-600",
			default: false,
		},
		{
			id: "next",
			name: "Next.js",
			description: "React framework with hybrid rendering",
			icon: "/icon/nextjs.svg",
			color: "from-gray-700 to-black",
			default: false,
		},
		{
			id: "nuxt",
			name: "Nuxt",
			description: "Vue full-stack framework (SSR, SSG, hybrid)",
			icon: "/icon/nuxt.svg",
			color: "from-green-400 to-green-700",
			default: false,
		},
		{
			id: "svelte",
			name: "Svelte",
			description: "Cybernetically enhanced web apps",
			icon: "/icon/svelte.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "solid",
			name: "Solid",
			description: "Simple and performant reactivity for building UIs",
			icon: "/icon/solid.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "none",
			name: "No Web Frontend",
			description: "No web-based frontend",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	nativeFrontend: [
		{
			id: "native-nativewind",
			name: "React Native + NativeWind",
			description: "Expo with NativeWind (Tailwind)",
			icon: "/icon/expo.svg",
			color: "from-purple-400 to-purple-600",
			className: "invert-0 dark:invert",
			default: false,
		},
		{
			id: "native-unistyles",
			name: "React Native + Unistyles",
			description: "Expo with Unistyles",
			icon: "/icon/expo.svg",
			color: "from-pink-400 to-pink-600",
			className: "invert-0 dark:invert",
			default: false,
		},
		{
			id: "none",
			name: "No Native Frontend",
			description: "No native mobile frontend",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	runtime: [
		{
			id: "bun",
			name: "Bun",
			description: "Fast JavaScript runtime & toolkit",
			icon: "/icon/bun.svg",
			color: "from-amber-400 to-amber-600",
			default: true,
		},
		{
			id: "node",
			name: "Node.js",
			description: "JavaScript runtime environment",
			icon: "/icon/node.svg",
			color: "from-green-400 to-green-600",
		},
		{
			id: "workers",
			name: "Cloudflare Workers",
			description: "Serverless runtime for the edge",
			icon: "/icon/workers.svg",
			color: "from-orange-400 to-orange-600",
		},
		{
			id: "none",
			name: "No Runtime",
			description: "No specific runtime",
			icon: "",
			color: "from-gray-400 to-gray-600",
		},
	],
	backend: [
		{
			id: "hono",
			name: "Hono",
			description: "Ultrafast web framework",
			icon: "/icon/hono.svg",
			color: "from-blue-500 to-blue-700",
			default: true,
		},
		{
			id: "next",
			name: "Next.js",
			description: "App Router and API Routes",
			icon: "/icon/nextjs.svg",
			color: "from-gray-700 to-black",
		},
		{
			id: "elysia",
			name: "Elysia",
			description: "TypeScript web framework",
			icon: "/icon/elysia.svg",
			color: "from-purple-500 to-purple-700",
		},
		{
			id: "express",
			name: "Express",
			description: "Popular Node.js framework",
			icon: "/icon/express.svg",
			color: "from-gray-500 to-gray-700",
		},
		{
			id: "fastify",
			name: "Fastify",
			description: "Fast, low-overhead web framework for Node.js",
			icon: "/icon/fastify.svg",
			color: "from-gray-500 to-gray-700",
		},
		{
			id: "convex",
			name: "Convex",
			description: "Reactive backend-as-a-service",
			icon: "/icon/convex.svg",
			color: "from-pink-500 to-pink-700",
		},
		{
			id: "none",
			name: "No Backend",
			description: "Skip backend integration (frontend only)",
			icon: "",
			color: "from-gray-400 to-gray-600",
		},
	],
	database: [
		{
			id: "sqlite",
			name: "SQLite",
			description: "File-based SQL database",
			icon: "/icon/sqlite.svg",
			color: "from-blue-400 to-cyan-500",
			default: true,
		},
		{
			id: "postgres",
			name: "PostgreSQL",
			description: "Advanced SQL database",
			icon: "/icon/postgres.svg",
			color: "from-indigo-400 to-indigo-600",
		},
		{
			id: "mysql",
			name: "MySQL",
			description: "Popular relational database",
			icon: "/icon/mysql.svg",
			color: "from-blue-500 to-blue-700",
		},
		{
			id: "mongodb",
			name: "MongoDB",
			description: "NoSQL document database",
			icon: "/icon/mongodb.svg",
			color: "from-green-400 to-green-600",
		},
		{
			id: "none",
			name: "No Database",
			description: "Skip database integration",
			icon: "",
			color: "from-gray-400 to-gray-600",
		},
	],
	orm: [
		{
			id: "drizzle",
			name: "Drizzle",
			description: "TypeScript ORM",
			icon: "/icon/drizzle.svg",
			color: "from-cyan-400 to-cyan-600",
			default: true,
		},
		{
			id: "prisma",
			name: "Prisma",
			description: "Next-gen ORM",
			icon: "/icon/prisma.svg",
			color: "from-purple-400 to-purple-600",
		},
		{
			id: "mongoose",
			name: "Mongoose",
			description: "Elegant object modeling tool",
			icon: "/icon/mongoose.svg",
			color: "from-blue-400 to-blue-600",
		},
		{
			id: "none",
			name: "No ORM",
			description: "Skip ORM integration",
			icon: "",
			color: "from-gray-400 to-gray-600",
		},
	],
	dbSetup: [
		{
			id: "turso",
			name: "Turso",
			description: "SQLite cloud database powered by libSQL",
			icon: "/icon/turso.svg",
			color: "from-pink-400 to-pink-600",
		},
		{
			id: "d1",
			name: "Cloudflare D1",
			description: "Serverless SQLite database on Cloudflare Workers",
			icon: "/icon/workers.svg",
			color: "from-orange-400 to-orange-600",
		},
		{
			id: "neon",
			name: "Neon Postgres",
			description: "Serverless PostgreSQL with Neon",
			icon: "/icon/neon.svg",
			color: "from-blue-400 to-blue-600",
		},
		{
			id: "prisma-postgres",
			name: "Prisma PostgreSQL",
			description: "Set up PostgreSQL with Prisma",
			icon: "/icon/prisma.svg",
			color: "from-indigo-400 to-indigo-600",
		},
		{
			id: "mongodb-atlas",
			name: "MongoDB Atlas",
			description: "Cloud MongoDB setup with Atlas",
			icon: "/icon/mongodb.svg",
			color: "from-green-400 to-green-600",
		},
		{
			id: "supabase",
			name: "Supabase",
			description: "Local Supabase stack (requires Docker)",
			icon: "/icon/supabase.svg",
			color: "from-emerald-400 to-emerald-600",
		},
		{
			id: "docker",
			name: "Docker",
			description: "Local database with Docker Compose",
			icon: "/icon/docker.svg",
			color: "from-blue-500 to-blue-700",
		},
		{
			id: "none",
			name: "Basic Setup",
			description: "No cloud DB integration",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: true,
		},
	],
	webDeploy: [
		{
			id: "workers",
			name: "Cloudflare Workers",
			description: "Deploy to Cloudflare Workers",
			icon: "/icon/workers.svg",
			color: "from-orange-400 to-orange-600",
		},
		{
			id: "none",
			name: "No Deployment",
			description: "Skip deployment configuration",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: true,
		},
	],
	auth: [
		{
			id: "bankid",
			name: "BankID (Norwegian)",
			description: "Norwegian digital identity with highest security",
			icon: "/icon/bankid.svg",
			color: "from-red-600 to-blue-800",
			default: false,
		},
		{
			id: "vipps",
			name: "Vipps Login",
			description: "Norwegian mobile payment and login",
			icon: "/icon/vipps.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "better-auth",
			name: "Better Auth",
			description: "Modern auth with social providers and 2FA",
			icon: "/icon/better-auth.svg",
			color: "from-blue-500 to-blue-700",
			default: true,
		},
		{
			id: "next-auth",
			name: "NextAuth.js",
			description: "Complete authentication solution for Next.js",
			icon: "/icon/nextauth.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "clerk",
			name: "Clerk",
			description: "Complete user management with UI components",
			icon: "/icon/clerk.svg",
			color: "from-indigo-500 to-indigo-700",
			default: false,
		},
		{
			id: "supabase-auth",
			name: "Supabase Auth",
			description: "Authentication with Supabase backend",
			icon: "/icon/supabase.svg",
			color: "from-emerald-500 to-emerald-700",
			default: false,
		},
		{
			id: "firebase-auth",
			name: "Firebase Auth",
			description: "Google Firebase authentication service",
			icon: "/icon/firebase.svg",
			color: "from-yellow-500 to-orange-600",
			default: false,
		},
		{
			id: "auth0",
			name: "Auth0",
			description: "Enterprise identity platform",
			icon: "/icon/auth0.svg",
			color: "from-orange-600 to-red-600",
			default: false,
		},
		{
			id: "custom",
			name: "Custom Auth",
			description: "Build your own authentication system",
			icon: "/icon/custom-auth.svg",
			color: "from-gray-500 to-gray-700",
			default: false,
		},
		{
			id: "none",
			name: "No Authentication",
			description: "Skip authentication setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	packageManager: [
		{
			id: "npm",
			name: "npm",
			description: "Default package manager",
			icon: "/icon/npm.svg",
			color: "from-red-500 to-red-700",
			className: "invert-0 dark:invert",
		},
		{
			id: "pnpm",
			name: "pnpm",
			description: "Fast, disk space efficient",
			icon: "/icon/pnpm.svg",
			color: "from-orange-500 to-orange-700",
		},
		{
			id: "bun",
			name: "bun",
			description: "All-in-one toolkit",
			icon: "/icon/bun.svg",
			color: "from-amber-500 to-amber-700",
			default: true,
		},
	],
	uiSystem: [
		{
			id: "xala",
			name: "Xala UI System v5",
			description: "Enterprise-grade design system with Norwegian compliance",
			icon: "/icon/xala.svg",
			color: "from-blue-600 to-purple-600",
			default: true,
		},
		{
			id: "shadcn",
			name: "shadcn/ui",
			description: "Beautifully designed components built with Radix UI",
			icon: "/icon/shadcn.svg",
			color: "from-gray-700 to-black",
			default: false,
		},
		{
			id: "tailwind",
			name: "Tailwind CSS",
			description: "Utility-first CSS framework",
			icon: "/icon/tailwind.svg",
			color: "from-cyan-400 to-cyan-600",
			default: false,
		},
		{
			id: "none",
			name: "No UI System",
			description: "Build custom components from scratch",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	compliance: [
		{
			id: "norwegian",
			name: "Norwegian Government",
			description: "BankID, Altinn, Digdir & NSM compliance",
			icon: "/icon/norway.svg",
			color: "from-red-600 to-blue-800",
			default: false,
		},
		{
			id: "gdpr",
			name: "GDPR Compliance",
			description: "EU data protection and privacy compliance",
			icon: "/icon/gdpr.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "wcag-aaa",
			name: "WCAG 2.2 AAA",
			description: "Highest level accessibility compliance",
			icon: "/icon/accessibility.svg",
			color: "from-green-500 to-green-700",
			default: false,
		},
		{
			id: "iso27001",
			name: "ISO 27001",
			description: "Information security management compliance",
			icon: "/icon/iso27001.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "none",
			name: "No Compliance",
			description: "Basic implementation without compliance features",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: true,
		},
	],
	addons: [
		{
			id: "pwa",
			name: "PWA (Progressive Web App)",
			description: "Make your app installable and work offline",
			icon: "",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "tauri",
			name: "Tauri",
			description: "Build native desktop apps",
			icon: "/icon/tauri.svg",
			color: "from-amber-500 to-amber-700",
			default: false,
		},
		{
			id: "starlight",
			name: "Starlight",
			description: "Build stellar docs with astro",
			icon: "/icon/starlight.svg",
			color: "from-teal-500 to-teal-700",
			default: false,
		},
		{
			id: "biome",
			name: "Biome",
			description: "Format, lint, and more",
			icon: "/icon/biome.svg",
			color: "from-green-500 to-green-700",
			default: false,
		},
		{
			id: "husky",
			name: "Husky",
			description: "Modern native Git hooks made easy",
			icon: "",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "ultracite",
			name: "Ultracite",
			description: "Biome preset with AI integration",
			icon: "/icon/ultracite.svg",
			color: "from-blue-500 to-blue-700",
			className: "invert-0 dark:invert",
			default: false,
		},
		{
			id: "fumadocs",
			name: "Fumadocs",
			description: "Build excellent documentation site",
			icon: "",
			color: "from-indigo-500 to-indigo-700",
			default: false,
		},
		{
			id: "oxlint",
			name: "Oxlint",
			description: "Rust-powered linter",
			icon: "",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "turborepo",
			name: "Turborepo",
			description: "High-performance build system",
			icon: "/icon/turborepo.svg",
			color: "from-gray-400 to-gray-700",
			default: true,
		},
	],
	examples: [
		{
			id: "todo",
			name: "Todo Example",
			description: "Simple todo application",
			icon: "",
			color: "from-indigo-500 to-indigo-700",
			default: false,
		},
		{
			id: "ai",
			name: "AI Example",
			description: "AI integration example using AI SDK",
			icon: "",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
	],
	git: [
		{
			id: "true",
			name: "Git",
			description: "Initialize Git repository",
			icon: "/icon/git.svg",
			color: "from-gray-500 to-gray-700",
			default: true,
		},
		{
			id: "false",
			name: "No Git",
			description: "Skip Git initialization",
			icon: "",
			color: "from-red-400 to-red-600",
		},
	],
	notifications: [
		{
			id: "resend",
			name: "Resend",
			description: "Email API for developers with React Email templates",
			icon: "/icon/resend.svg",
			color: "from-black to-gray-800",
			default: true,
		},
		{
			id: "nodemailer",
			name: "Nodemailer",
			description: "Send emails via SMTP with custom templates",
			icon: "/icon/nodemailer.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "sendgrid",
			name: "SendGrid",
			description: "Twilio SendGrid email delivery platform",
			icon: "/icon/sendgrid.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "mailgun",
			name: "Mailgun",
			description: "Email automation and delivery service",
			icon: "/icon/mailgun.svg",
			color: "from-red-500 to-red-700",
			default: false,
		},
		{
			id: "postmark",
			name: "Postmark",
			description: "Fast and reliable transactional email",
			icon: "/icon/postmark.svg",
			color: "from-yellow-500 to-orange-600",
			default: false,
		},
		{
			id: "pusher",
			name: "Pusher",
			description: "Real-time messaging and push notifications",
			icon: "/icon/pusher.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "twilio",
			name: "Twilio",
			description: "SMS, voice, and communication APIs",
			icon: "/icon/twilio.svg",
			color: "from-red-600 to-red-800",
			default: false,
		},
		{
			id: "none",
			name: "No Notifications",
			description: "Skip notification setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	documents: [
		{
			id: "uploadthing",
			name: "UploadThing",
			description: "File uploads for Next.js with type safety",
			icon: "/icon/uploadthing.svg",
			color: "from-red-500 to-red-700",
			default: true,
		},
		{
			id: "cloudinary",
			name: "Cloudinary",
			description: "Image and video management in the cloud",
			icon: "/icon/cloudinary.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "aws-s3",
			name: "AWS S3",
			description: "Amazon S3 object storage service",
			icon: "/icon/aws-s3.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "google-drive",
			name: "Google Drive API",
			description: "Google Drive file storage and management",
			icon: "/icon/google-drive.svg",
			color: "from-blue-400 to-green-500",
			default: false,
		},
		{
			id: "dropbox",
			name: "Dropbox API",
			description: "Dropbox file storage and sharing",
			icon: "/icon/dropbox.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "pdf-lib",
			name: "PDF Generation",
			description: "Create and manipulate PDF documents",
			icon: "/icon/pdf.svg",
			color: "from-red-500 to-red-700",
			default: false,
		},
		{
			id: "none",
			name: "No Document Services",
			description: "Skip document management setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	payments: [
		{
			id: "stripe",
			name: "Stripe",
			description: "Complete payment processing platform",
			icon: "/icon/stripe.svg",
			color: "from-purple-600 to-blue-600",
			default: true,
		},
		{
			id: "vipps-pay",
			name: "Vipps Payment",
			description: "Norwegian mobile payment solution",
			icon: "/icon/vipps.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "paypal",
			name: "PayPal",
			description: "PayPal payment processing",
			icon: "/icon/paypal.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "klarna",
			name: "Klarna",
			description: "Buy now, pay later payment solution",
			icon: "/icon/klarna.svg",
			color: "from-pink-500 to-pink-700",
			default: false,
		},
		{
			id: "square",
			name: "Square",
			description: "Square payment processing",
			icon: "/icon/square.svg",
			color: "from-gray-700 to-black",
			default: false,
		},
		{
			id: "adyen",
			name: "Adyen",
			description: "Global payment platform",
			icon: "/icon/adyen.svg",
			color: "from-green-600 to-green-800",
			default: false,
		},
		{
			id: "razorpay",
			name: "Razorpay",
			description: "Indian payment gateway",
			icon: "/icon/razorpay.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "none",
			name: "No Payments",
			description: "Skip payment integration",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	analytics: [
		{
			id: "vercel-analytics",
			name: "Vercel Analytics",
			description: "Privacy-friendly web analytics",
			icon: "/icon/vercel.svg",
			color: "from-black to-gray-800",
			default: true,
		},
		{
			id: "google-analytics",
			name: "Google Analytics",
			description: "Comprehensive web analytics platform",
			icon: "/icon/google-analytics.svg",
			color: "from-orange-500 to-red-600",
			default: false,
		},
		{
			id: "posthog",
			name: "PostHog",
			description: "Product analytics and feature flags",
			icon: "/icon/posthog.svg",
			color: "from-yellow-500 to-orange-600",
			default: false,
		},
		{
			id: "mixpanel",
			name: "Mixpanel",
			description: "Advanced product analytics",
			icon: "/icon/mixpanel.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "amplitude",
			name: "Amplitude",
			description: "Digital analytics and optimization",
			icon: "/icon/amplitude.svg",
			color: "from-blue-500 to-indigo-600",
			default: false,
		},
		{
			id: "hotjar",
			name: "Hotjar",
			description: "Heatmaps and user behavior analytics",
			icon: "/icon/hotjar.svg",
			color: "from-red-500 to-orange-600",
			default: false,
		},
		{
			id: "none",
			name: "No Analytics",
			description: "Skip analytics setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	monitoring: [
		{
			id: "sentry",
			name: "Sentry",
			description: "Application monitoring and error tracking",
			icon: "/icon/sentry.svg",
			color: "from-purple-600 to-pink-600",
			default: true,
		},
		{
			id: "datadog",
			name: "Datadog",
			description: "Infrastructure monitoring and APM",
			icon: "/icon/datadog.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "newrelic",
			name: "New Relic",
			description: "Full-stack observability platform",
			icon: "/icon/newrelic.svg",
			color: "from-green-500 to-teal-600",
			default: false,
		},
		{
			id: "grafana",
			name: "Grafana",
			description: "Open source analytics and monitoring",
			icon: "/icon/grafana.svg",
			color: "from-orange-500 to-red-600",
			default: false,
		},
		{
			id: "app-insights",
			name: "Azure App Insights",
			description: "Microsoft Azure application monitoring",
			icon: "/icon/azure-app-insights.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "prometheus",
			name: "Prometheus",
			description: "Open source monitoring and alerting",
			icon: "/icon/prometheus.svg",
			color: "from-orange-600 to-red-700",
			default: false,
		},
		{
			id: "elastic",
			name: "Elastic Stack",
			description: "Elasticsearch, Logstash, and Kibana",
			icon: "/icon/elastic.svg",
			color: "from-yellow-500 to-orange-600",
			default: false,
		},
		{
			id: "none",
			name: "No Monitoring",
			description: "Skip monitoring setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	messaging: [
		{
			id: "rabbitmq",
			name: "RabbitMQ",
			description: "Message broker for distributed systems",
			icon: "/icon/rabbitmq.svg",
			color: "from-orange-500 to-orange-700",
			default: true,
		},
		{
			id: "kafka",
			name: "Apache Kafka",
			description: "Distributed streaming platform",
			icon: "/icon/kafka.svg",
			color: "from-gray-700 to-black",
			default: false,
		},
		{
			id: "azure-service-bus",
			name: "Azure Service Bus",
			description: "Microsoft Azure messaging service",
			icon: "/icon/azure-service-bus.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "aws-sqs",
			name: "AWS SQS",
			description: "Amazon Simple Queue Service",
			icon: "/icon/aws-sqs.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "redis-pub-sub",
			name: "Redis Pub/Sub",
			description: "Redis publish/subscribe messaging",
			icon: "/icon/redis.svg",
			color: "from-red-500 to-red-700",
			default: false,
		},
		{
			id: "google-pub-sub",
			name: "Google Pub/Sub",
			description: "Google Cloud messaging service",
			icon: "/icon/google-pubsub.svg",
			color: "from-blue-400 to-green-500",
			default: false,
		},
		{
			id: "nats",
			name: "NATS",
			description: "High-performance messaging system",
			icon: "/icon/nats.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "none",
			name: "No Messaging",
			description: "Skip messaging setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	install: [
		{
			id: "true",
			name: "Install Dependencies",
			description: "Install packages automatically",
			icon: "",
			color: "from-green-400 to-green-600",
			default: true,
		},
		{
			id: "false",
			name: "Skip Install",
			description: "Skip dependency installation",
			icon: "",
			color: "from-yellow-400 to-yellow-600",
		},
	],
	testing: [
		{
			id: "jest",
			name: "Jest",
			description: "Delightful JavaScript testing framework",
			icon: "/icon/jest.svg",
			color: "from-red-500 to-red-700",
			default: true,
		},
		{
			id: "vitest",
			name: "Vitest",
			description: "Blazing fast unit test framework",
			icon: "/icon/vitest.svg",
			color: "from-green-500 to-green-700",
			default: false,
		},
		{
			id: "playwright",
			name: "Playwright",
			description: "End-to-end testing framework",
			icon: "/icon/playwright.svg",
			color: "from-blue-500 to-green-500",
			default: false,
		},
		{
			id: "cypress",
			name: "Cypress",
			description: "Fast, easy and reliable testing",
			icon: "/icon/cypress.svg",
			color: "from-gray-700 to-green-600",
			default: false,
		},
		{
			id: "k6",
			name: "k6",
			description: "Modern load testing tool",
			icon: "/icon/k6.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "none",
			name: "No Testing",
			description: "Skip testing setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	devops: [
		{
			id: "github-actions",
			name: "GitHub Actions",
			description: "CI/CD workflows for GitHub",
			icon: "/icon/github-actions.svg",
			color: "from-gray-800 to-blue-600",
			default: true,
		},
		{
			id: "docker",
			name: "Docker",
			description: "Containerization platform",
			icon: "/icon/docker.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "terraform",
			name: "Terraform",
			description: "Infrastructure as Code",
			icon: "/icon/terraform.svg",
			color: "from-purple-600 to-purple-800",
			default: false,
		},
		{
			id: "kubernetes",
			name: "Kubernetes",
			description: "Container orchestration platform",
			icon: "/icon/kubernetes.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "jenkins",
			name: "Jenkins",
			description: "Open source automation server",
			icon: "/icon/jenkins.svg",
			color: "from-blue-500 to-red-600",
			default: false,
		},
		{
			id: "none",
			name: "No DevOps",
			description: "Skip DevOps setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	search: [
		{
			id: "elasticsearch",
			name: "Elasticsearch",
			description: "Distributed search and analytics engine",
			icon: "/icon/elasticsearch.svg",
			color: "from-yellow-500 to-orange-600",
			default: true,
		},
		{
			id: "algolia",
			name: "Algolia",
			description: "Hosted search API",
			icon: "/icon/algolia.svg",
			color: "from-blue-500 to-purple-600",
			default: false,
		},
		{
			id: "meilisearch",
			name: "MeiliSearch",
			description: "Lightning fast search engine",
			icon: "/icon/meilisearch.svg",
			color: "from-pink-500 to-purple-600",
			default: false,
		},
		{
			id: "typesense",
			name: "Typesense",
			description: "Fast, typo-tolerant search engine",
			icon: "/icon/typesense.svg",
			color: "from-blue-600 to-indigo-700",
			default: false,
		},
		{
			id: "none",
			name: "No Search",
			description: "Skip search setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	caching: [
		{
			id: "redis",
			name: "Redis",
			description: "In-memory data structure store",
			icon: "/icon/redis.svg",
			color: "from-red-500 to-red-700",
			default: true,
		},
		{
			id: "memcached",
			name: "Memcached",
			description: "High-performance distributed memory caching",
			icon: "/icon/memcached.svg",
			color: "from-green-500 to-green-700",
			default: false,
		},
		{
			id: "cloudflare",
			name: "Cloudflare",
			description: "Global CDN and edge computing",
			icon: "/icon/cloudflare.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "aws-cloudfront",
			name: "AWS CloudFront",
			description: "Amazon content delivery network",
			icon: "/icon/aws-cloudfront.svg",
			color: "from-orange-500 to-orange-700",
			default: false,
		},
		{
			id: "none",
			name: "No Caching",
			description: "Skip caching setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	backgroundJobs: [
		{
			id: "bullmq",
			name: "BullMQ",
			description: "Premium queue package for handling distributed jobs",
			icon: "/icon/bullmq.svg",
			color: "from-red-600 to-red-800",
			default: true,
		},
		{
			id: "agenda",
			name: "Agenda",
			description: "Lightweight job scheduling for Node.js",
			icon: "/icon/agenda.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "inngest",
			name: "Inngest",
			description: "Durable workflow engine",
			icon: "/icon/inngest.svg",
			color: "from-purple-500 to-purple-700",
			default: false,
		},
		{
			id: "temporal",
			name: "Temporal",
			description: "Microservice orchestration platform",
			icon: "/icon/temporal.svg",
			color: "from-blue-600 to-indigo-700",
			default: false,
		},
		{
			id: "none",
			name: "No Background Jobs",
			description: "Skip background job setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	i18n: [
		{
			id: "next-intl",
			name: "next-intl",
			description: "Internationalization for Next.js",
			icon: "/icon/next-intl.svg",
			color: "from-blue-500 to-blue-700",
			default: true,
		},
		{
			id: "react-i18next",
			name: "react-i18next",
			description: "Internationalization framework for React",
			icon: "/icon/react-i18next.svg",
			color: "from-blue-400 to-cyan-500",
			default: false,
		},
		{
			id: "formatjs",
			name: "FormatJS",
			description: "Modular collection of JavaScript libraries",
			icon: "/icon/formatjs.svg",
			color: "from-orange-500 to-red-600",
			default: false,
		},
		{
			id: "crowdin",
			name: "Crowdin",
			description: "Translation management platform",
			icon: "/icon/crowdin.svg",
			color: "from-green-500 to-green-700",
			default: false,
		},
		{
			id: "none",
			name: "No Internationalization",
			description: "Skip i18n setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	cms: [
		{
			id: "strapi",
			name: "Strapi",
			description: "Leading open-source headless CMS",
			icon: "/icon/strapi.svg",
			color: "from-purple-600 to-purple-800",
			default: true,
		},
		{
			id: "contentful",
			name: "Contentful",
			description: "API-first content management platform",
			icon: "/icon/contentful.svg",
			color: "from-blue-500 to-blue-700",
			default: false,
		},
		{
			id: "sanity",
			name: "Sanity",
			description: "Platform for structured content",
			icon: "/icon/sanity.svg",
			color: "from-red-500 to-red-700",
			default: false,
		},
		{
			id: "payload",
			name: "Payload CMS",
			description: "TypeScript headless CMS",
			icon: "/icon/payload.svg",
			color: "from-gray-700 to-gray-900",
			default: false,
		},
		{
			id: "ghost",
			name: "Ghost",
			description: "Professional publishing platform",
			icon: "/icon/ghost.svg",
			color: "from-gray-800 to-black",
			default: false,
		},
		{
			id: "none",
			name: "No CMS",
			description: "Skip CMS setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
	security: [
		{
			id: "snyk",
			name: "Snyk",
			description: "Developer security platform",
			icon: "/icon/snyk.svg",
			color: "from-purple-600 to-purple-800",
			default: true,
		},
		{
			id: "sonarqube",
			name: "SonarQube",
			description: "Code quality and security analysis",
			icon: "/icon/sonarqube.svg",
			color: "from-blue-600 to-blue-800",
			default: false,
		},
		{
			id: "owasp-zap",
			name: "OWASP ZAP",
			description: "Web application security scanner",
			icon: "/icon/owasp.svg",
			color: "from-red-600 to-red-800",
			default: false,
		},
		{
			id: "semgrep",
			name: "Semgrep",
			description: "Static analysis tool for security",
			icon: "/icon/semgrep.svg",
			color: "from-green-600 to-green-800",
			default: false,
		},
		{
			id: "none",
			name: "No Security Scanning",
			description: "Skip security setup",
			icon: "",
			color: "from-gray-400 to-gray-600",
			default: false,
		},
	],
};

export const PRESET_TEMPLATES = [
	{
		id: "default",
		name: "Default Stack",
		description: "Standard web app with TanStack Router, Bun, Hono and SQLite",
		stack: {
			projectName: "my-xaheen-t-app",
			webFrontend: ["tanstack-router"],
			nativeFrontend: ["none"],
			runtime: "bun",
			backend: "hono",
			database: "sqlite",
			orm: "drizzle",
			dbSetup: "none",
			auth: "true",
			packageManager: "bun",
			addons: ["turborepo"],
			examples: [],
			git: "true",
			install: "true",
			api: "trpc",
		},
	},
	{
		id: "convex-react",
		name: "Convex + React",
		description: "Reactive full-stack app with Convex and TanStack Router",
		stack: {
			projectName: "my-xaheen-t-app",
			webFrontend: ["tanstack-router"],
			nativeFrontend: ["none"],
			backend: "convex",
			runtime: "none",
			database: "none",
			orm: "none",
			dbSetup: "none",
			auth: "false",
			packageManager: "bun",
			addons: ["turborepo"],
			examples: ["todo"],
			git: "true",
			install: "true",
			api: "none",
		},
	},
	{
		id: "native-app",
		name: "Mobile App",
		description: "React Native with Expo and SQLite database",
		stack: {
			projectName: "my-xaheen-t-app",
			webFrontend: ["none"],
			nativeFrontend: ["native-nativewind"],
			runtime: "bun",
			backend: "hono",
			database: "sqlite",
			orm: "drizzle",
			dbSetup: "none",
			auth: "true",
			packageManager: "bun",
			addons: ["turborepo"],
			examples: [],
			git: "true",
			install: "true",
			api: "trpc",
		},
	},
	{
		id: "api-only",
		name: "API Only",
		description: "Backend API with Hono and Sqlite",
		stack: {
			projectName: "my-xaheen-t-app",
			webFrontend: ["none"],
			nativeFrontend: ["none"],
			runtime: "bun",
			backend: "hono",
			database: "sqlite",
			orm: "drizzle",
			dbSetup: "none",
			auth: "true",
			packageManager: "bun",
			addons: ["turborepo"],
			examples: [],
			git: "true",
			install: "true",
			api: "trpc",
		},
	},
	{
		id: "full-featured",
		name: "Full Featured",
		description: "Complete setup with web, native, Turso, and addons",
		stack: {
			projectName: "my-xaheen-t-app",
			webFrontend: ["tanstack-router"],
			nativeFrontend: ["native-nativewind"],
			runtime: "bun",
			backend: "hono",
			database: "sqlite",
			orm: "drizzle",
			dbSetup: "turso",
			auth: "true",
			packageManager: "bun",
			addons: ["pwa", "biome", "husky", "tauri", "starlight", "turborepo"],
			examples: ["todo", "ai"],
			git: "true",
			install: "true",
			api: "trpc",
		},
	},
];

export type StackState = {
	projectName: string;
	webFrontend: string[];
	nativeFrontend: string[];
	runtime: string;
	backend: string;
	database: string;
	orm: string;
	dbSetup: string;
	auth: string;
	packageManager: string;
	uiSystem: string;
	compliance: string[];
	addons: string[];
	notifications: string;
	documents: string;
	payments: string;
	analytics: string;
	monitoring: string;
	messaging: string;
	examples: string[];
	git: string;
	install: string;
	api: string;
	webDeploy: string;
};

export const DEFAULT_STACK: StackState = {
	projectName: "my-xaheen-t-app",
	webFrontend: ["tanstack-router"],
	nativeFrontend: ["none"],
	runtime: "bun",
	backend: "hono",
	database: "sqlite",
	orm: "drizzle",
	dbSetup: "none",
	auth: "better-auth",
	packageManager: "bun",
	uiSystem: "xala",
	compliance: ["none"],
	addons: ["turborepo"],
	notifications: "resend",
	documents: "uploadthing",
	payments: "stripe",
	analytics: "vercel-analytics",
	monitoring: "sentry",
	messaging: "rabbitmq",
	examples: [],
	git: "true",
	install: "true",
	api: "trpc",
	webDeploy: "none",
};

export const isStackDefault = <K extends keyof StackState>(
	stack: StackState,
	key: K,
	value: StackState[K],
): boolean => {
	const defaultValue = DEFAULT_STACK[key];

	if (stack.backend === "convex") {
		if (key === "runtime" && value === "none") return true;
		if (key === "database" && value === "none") return true;
		if (key === "orm" && value === "none") return true;
		if (key === "api" && value === "none") return true;
		if (key === "auth" && value === "false") return true;
		if (key === "dbSetup" && value === "none") return true;
		if (
			key === "examples" &&
			Array.isArray(value) &&
			value.length === 1 &&
			value[0] === "todo"
		)
			return true;
	}

	if (key === "webFrontend" && stack.webFrontend) {
		if (key === "webFrontend") {
			const defaultWeb = (DEFAULT_STACK.webFrontend as string[]).sort();
			const valueWeb = (value as string[]).sort();
			return (
				defaultWeb.length === valueWeb.length &&
				defaultWeb.every((item, index) => item === valueWeb[index])
			);
		}
	}

	if (Array.isArray(defaultValue) && Array.isArray(value)) {
		const sortedDefault = [...defaultValue].sort();
		const sortedValue = [...value].sort();
		return (
			sortedDefault.length === sortedValue.length &&
			sortedDefault.every((item, index) => item === sortedValue[index])
		);
	}
	return defaultValue === value;
};
